POST http://localhost:3001/user/login
content-type: application/json

{
    "name": "v4",
    "password": "isdawae",
    "token": "xxxxxxxx"
}

###

POST http://localhost:3001/user/verify
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJuYW1lIjoidjQiLCJpYXQiOjE2NDMwNDA2MTh9.LvNcdIbg2Q5ovw1-2g2UZmWVtIFGXNxLnEP1KIjygok

###

POST http://localhost:3001/tests/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJuYW1lIjoidjQiLCJpYXQiOjE2NDMwNDA2MTh9.LvNcdIbg2Q5ovw1-2g2UZmWVtIFGXNxLnEP1KIjygok

{
    "length": 10,
    "difficulty": "hard"
}

###

POST http://localhost:3001/tests/new
Content-Type: application/json

{
    "length": 10,
    "difficulty": "medium"
}


###
// neplatne jwt
POST http://localhost:3001/tests/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

{
    "length": 50,
    "difficulty": "medium"
}

###

GET http://localhost:3001/tests/65/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJuYW1lIjoidjQiLCJpYXQiOjE2NDMwNDA2MTh9.LvNcdIbg2Q5ovw1-2g2UZmWVtIFGXNxLnEP1KIjygok
