POST http://localhost:3001/user/login
content-type: application/json

{
    "name": "v4",
    "password": "isdawae"
}

###

POST http://localhost:3001/user/verify
content-type: application/json

{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJuYW1lIjoidjQiLCJpYXQiOjE2NDMwNDA2MTh9.LvNcdIbg2Q5ovw1-2g2UZmWVtIFGXNxLnEP1KIjygok"
}